### ISSUE TITLE
Interactivate Visualization

### ISSUE THREAD

**Issue by happywu** [epfml/attention-cnn#7]
Hi,

Where can I find the code for interactive visualization or could you provide some guidance to implement this?

Thanks,
Haiping

**Comment by jbcdnr** [comment]
Hello, 
It is implemented with some dirty Svelte.js serving pre computed matplotlib figures. Right now the code is too ugly to be shared publicly 🙈 but in the meantime I can email you the current code. Just drop me an email :)

**Comment by happywu** [comment]
Thanks!

**Comment by jbdel** [comment]
Hello, 

Sorry for re-opening this thread. Are the precomputed matplotlib figure used for the interactive demo generated with this script : https://github.com/epfml/attention-cnn/blob/master/utils/plotting.py ?

Or lets say I have attn weight of size bs, width, height, num_head, width, height, what can I expect as output from the script plotting.py ?

Thanks !

**Comment by askerlee** [comment]
@jbcdnr Do you mean all the attention map figures are pre-generated? Oh that will be a lot... Not sure how difficult it is to develop a GUI-based visualizer. Guess it would be easier to create one that runs on local PC.

**Comment by hzphzp** [comment]
> Hello,
> It is implemented with some dirty Svelte.js serving pre computed matplotlib figures. Right now the code is too ugly to be shared publicly 🙈 but in the meantime I can email you the current code. Just drop me an email :)

Hi, thank you for you excellent works, could you please share me the Interactivate Visualization code? My email address is hzp1104@mail.ustc.edu.cn
